/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-24 04:26:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.manager;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class milestoneManagerStatistics_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/inyeo/Desktop/jsp/workspace/milestone/WebContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/Users/inyeo/Desktop/jsp/workspace/milestone/WebContent/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1664872564000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>이정표 | 관리자페이지</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/manager/mileStoneManager_all_css.css\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"showClock()\">\r\n");
      out.write("	<!-- 사이드 -->\r\n");
      out.write("	<div id='sidebar'>\r\n");
      out.write("		<div id='sidebar_header'>\r\n");
      out.write("			<a\r\n");
      out.write("				href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/management/managerDonateHistory.don\"\r\n");
      out.write("				id=\"mileStoneLogo\"> </a>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"sidebar_menu\">\r\n");
      out.write("			<div id=\"sidebar_menu_wrapper\">\r\n");
      out.write("				<div class=\"menu menu_colum\">\r\n");
      out.write("					<!-- 대시 보드 -->\r\n");
      out.write("					<div class=\"menu_item\">\r\n");
      out.write("						<span class=\"menu-link\"> <span class=\"menu-icon\"> <span\r\n");
      out.write("								id=\"dashboard-icon-img\"></span>\r\n");
      out.write("						</span> <span class=\"menu-title\">대시보드</span> <span class=\"menu-arrow\">\r\n");
      out.write("								<span class=\"arrow-icon\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"menu-sub\">\r\n");
      out.write("							<div class=\"menu-item\" onclick=\"javascript:btn()\"> \r\n");
      out.write("								<a class=\"menu-link active\"\r\n");
      out.write("									href=\"\">\r\n");
      out.write("									<span class=\"menu-bullet\"> <span class=\"bullet\"></span>\r\n");
      out.write("								</span> <span class=\"menu-title\">이용자 통계</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"menu-item\">\r\n");
      out.write("								<a class=\"menu-link active\"\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/management/managerDonateHistory.don\">\r\n");
      out.write("									<span class=\"menu-bullet\"> <span class=\"bullet\"></span>\r\n");
      out.write("								</span> <span class=\"menu-title\">기부 내역</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"menu-item pt-5\">\r\n");
      out.write("						<div class=\"menu-content\">\r\n");
      out.write("							<span class=\"menu-heading\">페이지</span>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 사용자 관리 -->\r\n");
      out.write("					<div class=\"menu_item\">\r\n");
      out.write("						<span class=\"menu-link\"> <span class=\"menu-icon\"> <span\r\n");
      out.write("								id=\"user-icon-img\"></span>\r\n");
      out.write("						</span> <span class=\"menu-title\">사용자 관리</span> <span class=\"menu-arrow\">\r\n");
      out.write("								<span class=\"arrow-icon\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"menu-sub\">\r\n");
      out.write("							<div class=\"menu-item\">\r\n");
      out.write("								<a class=\"menu-link active\"\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/management/userList.me\">\r\n");
      out.write("									<span class=\"menu-bullet\"> <span class=\"bullet\"></span>\r\n");
      out.write("								</span> <span class=\"menu-title\">사용자 목록</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 커뮤니티 관리 -->\r\n");
      out.write("					<div class=\"menu_item\">\r\n");
      out.write("						<span class=\"menu-link\"> <span class=\"menu-icon\"> <span\r\n");
      out.write("								id=\"coumunity-icon-img\"></span>\r\n");
      out.write("						</span> <span class=\"menu-title\">커뮤니티 관리</span> <span class=\"menu-arrow\">\r\n");
      out.write("								<span class=\"arrow-icon\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"menu-sub\">\r\n");
      out.write("							<div class=\"menu-item\">\r\n");
      out.write("								<a class=\"menu-link active\"\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/management/communityManager.manager\">\r\n");
      out.write("									<span class=\"menu-bullet\"> <span class=\"bullet\"></span>\r\n");
      out.write("								</span> <span class=\"menu-title\">게시글 목록</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 기부 일정 관리 -->\r\n");
      out.write("					<div class=\"menu_item\">\r\n");
      out.write("						<span class=\"menu-link\"> <span class=\"menu-icon\"> <span\r\n");
      out.write("								id=\"schedule-icon-img\"></span>\r\n");
      out.write("						</span> <span class=\"menu-title\">기부 일정 관리</span> <span class=\"menu-arrow\">\r\n");
      out.write("								<span class=\"arrow-icon\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"menu-sub\">\r\n");
      out.write("							<div class=\"menu-item\" onclick=\"javascript:btn()\">\r\n");
      out.write("								<a class=\"menu-link active\"\r\n");
      out.write("									href=\"\">\r\n");
      out.write("									<span class=\"menu-bullet\"> <span class=\"bullet\"></span>\r\n");
      out.write("								</span> <span class=\"menu-title\">기부 일정 달력</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 고객지원 -->\r\n");
      out.write("					<div class=\"menu_item\">\r\n");
      out.write("						<span class=\"menu-link\"> <span class=\"menu-icon\"> <span\r\n");
      out.write("								id=\"supportGuest-icon-img\"></span>\r\n");
      out.write("						</span> <span class=\"menu-title\">공지사항</span> <span class=\"menu-arrow\">\r\n");
      out.write("								<span class=\"arrow-icon\"></span>\r\n");
      out.write("						</span>\r\n");
      out.write("						</span>\r\n");
      out.write("						<div class=\"menu-sub\">\r\n");
      out.write("							<div class=\"menu-item\">\r\n");
      out.write("								<a class=\"menu-link active\"\r\n");
      out.write("									href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/management/managerNoticeListOk.notice\">\r\n");
      out.write("									<span class=\"menu-bullet\"> <span class=\"bullet\"></span>\r\n");
      out.write("								</span> <span class=\"menu-title\">공지사항 관리</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"menu-item\" onclick=\"javascript:btn()\">\r\n");
      out.write("								<a class=\"menu-link active\"\r\n");
      out.write("									href=\"\">\r\n");
      out.write("									<span class=\"menu-bullet\"> <span class=\"bullet\"></span>\r\n");
      out.write("								</span> <span class=\"menu-title\">배너 관리</span>\r\n");
      out.write("								</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- 헤더 -->\r\n");
      out.write("	<header>\r\n");
      out.write("		<div id=\"header\">\r\n");
      out.write("			<a href=\"https://playwarcraft3.com/ko-kr/\" class=\"banner\"></a>\r\n");
      out.write("			<div id=\"toolBox\">\r\n");
      out.write("				<div id=\"divClock\" class=\"clock\"></div>\r\n");
      out.write("				<div>관리자님 환영합니다.</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- 메인 -->\r\n");
      out.write("	<main>\r\n");
      out.write("		<div class=\"main\">\r\n");
      out.write("			<div id=\"toolbar\">\r\n");
      out.write("				<div id=\"toolbarTitle\">\r\n");
      out.write("					<span id=\"toolbarTitleText\">이용자 통계</span> <span\r\n");
      out.write("						id=\"toolbarTitleSub\">홈 - 대시보드 - 이용자 통계</span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 메인 컨텐츠 -->\r\n");
      out.write("			<div id=\"content-container\">\r\n");
      out.write("				<div class=\"row-content-container\">\r\n");
      out.write("					<!-- 종합, 보육원 세로 그래프 -->\r\n");
      out.write("					<div class=\"colum-content-container\">\r\n");
      out.write("						<div class=\"cardAll card4of1\">\r\n");
      out.write("							<div class=\"card-header-chart\">\r\n");
      out.write("								<div class=\"card-title-chart\">\r\n");
      out.write("									<div class=\"flex-card-Title\">\r\n");
      out.write("										<span class=\"card-Title-value\">2477명</span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<span class=\"card-Title-text\">일일 종합 방문자수 비율</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body-chart\">\r\n");
      out.write("								<div id=\"synthesisPieChart\" style=\"width: 90px; height: 90px;\"></div>\r\n");
      out.write("								<div class=\"chart-legend-colum\">\r\n");
      out.write("									<div class=\"chart-legend-flex\">\r\n");
      out.write("										<div class=\"bullet chart-legned-bullet general\"></div>\r\n");
      out.write("										<div class=\"chart-legend-flex-text\">일반 회원</div>\r\n");
      out.write("										<div class=\"chart-legend-flex-value\">456명</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"chart-legend-flex\">\r\n");
      out.write("										<div class=\"bullet chart-legned-bullet nurserySchool\"></div>\r\n");
      out.write("										<div class=\"chart-legend-flex-text\">보육원 회원</div>\r\n");
      out.write("										<div class=\"chart-legend-flex-value\">150명</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"chart-legend-flex\">\r\n");
      out.write("										<div class=\"bullet chart-legned-bullet nonMember\"></div>\r\n");
      out.write("										<div class=\"chart-legend-flex-text\">비회원</div>\r\n");
      out.write("										<div class=\"chart-legend-flex-value\">1871명</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"cardAll card4of1\">\r\n");
      out.write("							<div class=\"card-header-chart\">\r\n");
      out.write("								<div class=\"card-title-chart\">\r\n");
      out.write("									<div class=\"flex-card-Title\">\r\n");
      out.write("										<span class=\"card-Title-value\">150명</span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<span class=\"card-Title-text\">일일 보육원회원 방문수</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body-chart\">\r\n");
      out.write("								<div id=\"nurserySchoolLineChart\"\r\n");
      out.write("									style=\"width: 100%; height: 160px\"></div>\r\n");
      out.write("								<div class=\"chart-legend-colum\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 일반회원, 비회원 세로 그래프 -->\r\n");
      out.write("					<div class=\"colum-content-container\">\r\n");
      out.write("						<div class=\"cardAll card4of1\">\r\n");
      out.write("							<div class=\"card-header-chart\">\r\n");
      out.write("								<div class=\"card-title-chart\">\r\n");
      out.write("									<div class=\"flex-card-Title\">\r\n");
      out.write("										<span class=\"card-Title-value\">456명</span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<span class=\"card-Title-text\">일일 일반회원 방문수</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body-chart\">\r\n");
      out.write("								<div id=\"generalLineChart\" style=\"width: 100%; height: 160px\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"cardAll card4of1\">\r\n");
      out.write("							<div class=\"card-header-chart\">\r\n");
      out.write("								<div class=\"card-title-chart\">\r\n");
      out.write("									<div class=\"flex-card-Title\">\r\n");
      out.write("										<span class=\"card-Title-value\">1871명</span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<span class=\"card-Title-text\">일일 비회원 방문수</span>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body-chart\">\r\n");
      out.write("								<div id=\"nonMemberLineChart\" style=\"width: 100%; height: 160px\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 종합 방문수 그래프 -->\r\n");
      out.write("					<div class=\"colum-content-container\">\r\n");
      out.write("						<div class=\"cardAll card1of1\">\r\n");
      out.write("							<div class=\"card-header-chart\">\r\n");
      out.write("								<div class=\"card-title-chart\">\r\n");
      out.write("									<div class=\"flex-card-Title\">\r\n");
      out.write("										<span class=\"card-Title-1of1\">통계</span>\r\n");
      out.write("									</div>\r\n");
      out.write("									<span class=\"card-Title-text\">종합 방문자수</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"card-toolbar-chart\">\r\n");
      out.write("									<div class=\"select-dayormonth\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"card-body-1of1\">\r\n");
      out.write("								<div class=\"card-body-title\">\r\n");
      out.write("									<div class=\"card-title-value-1of1\">2477명</div>\r\n");
      out.write("									<span class=\"card-Title-text\">일일 방문자수</span>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"chart-wrap\">\r\n");
      out.write("									<div id=\"synthesisLineChart\" style=\"width: 100%; height: 100%\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- 푸터 -->\r\n");
      out.write("			<footer>\r\n");
      out.write("				<div id=\"footer-logo-box\">\r\n");
      out.write("\r\n");
      out.write("					<div id=\"footer-flex\">\r\n");
      out.write("\r\n");
      out.write("						<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/index.me\">\r\n");
      out.write("							<div id=\"footer-logo\"></div>\r\n");
      out.write("						</a>\r\n");
      out.write("						<div id=\"footer-company\">2022© 동석한 아카데미 Team 4</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"footer-flex\">\r\n");
      out.write("					<div id=\"footer-menu\">이용약관 · 개인정보 처리방침 · 이용약관 · 사업자 정보 확인 ·\r\n");
      out.write("						제휴/협력 · 문의 단체/기업 교육 문의</div>\r\n");
      out.write("					<div id=\"footer-company-info\">대표 김의엽 | 서울 강남구 테헤란로 146\r\n");
      out.write("						3층(역삼동) | T4@.inc | 전화번호: 1234-1234 |</div>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</footer>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("	src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.slim.min.js\"\r\n");
      out.write("	integrity=\"sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	var jb = jQuery.noConflict();\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.1.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/manager/mileStoneManager_public.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/manager/mileStoneManager_statistics.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	function btn() {\r\n");
      out.write("		alert('준비중입니다.');\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
