/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-13 04:24:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1664872564000L));
    _jspx_dependants.put("jar:file:/C:/Users/inyeo/Desktop/jsp/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML>\r\n");
      out.write("<!--\r\n");
      out.write("	Altitude by Pixelarity\r\n");
      out.write("	pixelarity.com | hello@pixelarity.com\r\n");
      out.write("	License: pixelarity.com/license\r\n");
      out.write("-->\r\n");
      out.write("<html>\r\n");
      out.write("	<head>\r\n");
      out.write("		<title>로그인</title>\r\n");
      out.write("		<meta charset=\"utf-8\" />\r\n");
      out.write("		<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("		<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/main.css\" />\r\n");
      out.write("		<style>\r\n");
      out.write("			input[type='button'], input[type='submit']{border-radius:0;}\r\n");
      out.write("			textarea{resize:none;}\r\n");
      out.write("			label{margin-top:3%;}\r\n");
      out.write("			div.preview{overflow:hidden;}\r\n");
      out.write("			div.preview img{width:90%; object-fit:cover; margin-left:10%;}\r\n");
      out.write("		</style>\r\n");
      out.write("	</head>\r\n");
      out.write("	<body class=\"is-preload\">\r\n");
      out.write("		");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<!-- Page Wrapper -->\r\n");
      out.write("			<div id=\"page-wrapper\">\r\n");
      out.write("\r\n");
      out.write("				<!-- Wrapper -->\r\n");
      out.write("					<div class=\"wrapper\">\r\n");
      out.write("						<div class=\"inner\">\r\n");
      out.write("							");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, (java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}/app/fix/header.jsp", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null), out, false);
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- Wrapper -->\r\n");
      out.write("					<div class=\"wrapper\">\r\n");
      out.write("						<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Main -->\r\n");
      out.write("							<section class=\"main\">\r\n");
      out.write("\r\n");
      out.write("								<header class=\"major\">\r\n");
      out.write("									<a href=\"#\" class=\"image main\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/login01.png\" alt=\"\" /></a>\r\n");
      out.write("									<h1>로그인</h1>\r\n");
      out.write("								</header>\r\n");
      out.write("								<hr />\r\n");
      out.write("								<form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/loginOk.me\" name=\"loginForm\">\r\n");
      out.write("									<div style=\"display:flex; justify-content:space-evenly;\">\r\n");
      out.write("										<div style=\"width:40%\">\r\n");
      out.write("												<div>\r\n");
      out.write("													<div class=\"col-6 col-12-xsmall\" style=\"width:100%\">\r\n");
      out.write("														<p style=\"margin:0;\">아이디 </p>\r\n");
      out.write("														<input type=\"text\" name=\"memberId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty memberId ? '' : memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("														<br>\r\n");
      out.write("														<p style=\"margin:0;\">비밀번호</p>\r\n");
      out.write("														<input type=\"password\" name=\"memberPw\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty memberPw ? '' : memberPw}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("														\r\n");
      out.write("														<div class=\"col-12\" style=\"display:flex; justify-content:flex-start; margin-top: 20px;\">\r\n");
      out.write("															<div>\r\n");
      out.write("																<input type=\"checkbox\" id=\"saveId\" name=\"saveId\" value=\"saveId\"> \r\n");
      out.write("																<label for=\"saveId\">아이디 저장 </label>\r\n");
      out.write("															</div>\r\n");
      out.write("															<div>\r\n");
      out.write("																<input type=\"checkbox\" id=\"autoLogin\" name=\"autoLogin\" value=\"autoLogin\"> \r\n");
      out.write("																<label for=\"autoLogin\">자동 로그인</label>\r\n");
      out.write("															</div>\r\n");
      out.write("														</div>\r\n");
      out.write("													</div>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"col-12\">\r\n");
      out.write("													<ul class=\"actions\" style=\"display:block; text-align:center; margin-top:9%\">\r\n");
      out.write("														<li><input type=\"button\" value=\"로그인\" class=\"primary\" style=\"width:100%; font-size:1em;\" onclick=\"send()\"/></li>\r\n");
      out.write("														<li><input type=\"button\" value=\"회원가입\" style=\"width:100%; font-size:1em;\" onclick=\"location.href = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/join.me'\" /></li>\r\n");
      out.write("													</ul>\r\n");
      out.write("												</div>	\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"preview\" style=\"width:40%\">\r\n");
      out.write("												<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/login02.png\">\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</form>\r\n");
      out.write("							</section>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				<!-- Wrapper -->\r\n");
      out.write("					<div class=\"wrapper\">\r\n");
      out.write("						<div class=\"inner\">\r\n");
      out.write("\r\n");
      out.write("							<!-- Footer -->\r\n");
      out.write("								<footer id=\"footer\">\r\n");
      out.write("									<section class=\"links\">\r\n");
      out.write("										<div>\r\n");
      out.write("											<h3>Magna</h3>\r\n");
      out.write("											<ul class=\"plain\">\r\n");
      out.write("												<li><a href=\"#\">Aliquam tempus</a></li>\r\n");
      out.write("												<li><a href=\"#\">Ultrecies nul</a></li>\r\n");
      out.write("												<li><a href=\"#\">Gravida ultricies</a></li>\r\n");
      out.write("												<li><a href=\"#\">Commodo etiam</a></li>\r\n");
      out.write("												</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div>\r\n");
      out.write("											<h3>Feugiat</h3>\r\n");
      out.write("											<ul class=\"plain\">\r\n");
      out.write("												<li><a href=\"#\">Morbi sem lorem</a></li>\r\n");
      out.write("												<li><a href=\"#\">Praes sed dapi</a></li>\r\n");
      out.write("												<li><a href=\"#\">Sed adipis nullam</a></li>\r\n");
      out.write("												<li><a href=\"#\">Fus dolor lacinia</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div>\r\n");
      out.write("											<h3>Tempus</h3>\r\n");
      out.write("											<ul class=\"plain\">\r\n");
      out.write("												<li><a href=\"#\">Donecnec etiam</a></li>\r\n");
      out.write("												<li><a href=\"#\">Aapibus sedun</a></li>\r\n");
      out.write("												<li><a href=\"#\">Namnulla tempus</a></li>\r\n");
      out.write("												<li><a href=\"#\">Morbi set amet</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div>\r\n");
      out.write("											<h3>Aliquam</h3>\r\n");
      out.write("											<ul class=\"plain\">\r\n");
      out.write("												<li><a href=\"#\">Lorem prasent dia</a></li>\r\n");
      out.write("												<li><a href=\"#\">Nellentes ipsum</a></li>\r\n");
      out.write("												<li><a href=\"#\">Diamsed arcu dolor</a></li>\r\n");
      out.write("												<li><a href=\"#\">Sit amet cursus</a></li>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("									</section>\r\n");
      out.write("									<ul class=\"contact-icons\">\r\n");
      out.write("										<li class=\"icon solid fa-home\">1234 Fictional Street #5432 Nashville, TN 00000-0000</li>\r\n");
      out.write("										<li class=\"icon solid fa-phone\"><a href=\"#\">(000) 000-0000</a></li>\r\n");
      out.write("										<li class=\"icon solid fa-envelope\"><a href=\"#\">info@untitled.tld</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("									<p class=\"copyright\">&copy; Untitled. All rights reserved.</p>\r\n");
      out.write("								</footer>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("			</div>\r\n");
      out.write("	</body>\r\n");
      out.write("	<!-- Scripts -->\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/browser.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/breakpoints.min.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/util.js\"></script>\r\n");
      out.write("	<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/main.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		function send(){\r\n");
      out.write("			let id = loginForm.memberId.value;\r\n");
      out.write("			let pw = loginForm.memberPw.value;\r\n");
      out.write("			\r\n");
      out.write("			if(!id){\r\n");
      out.write("				loginForm.memberId.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			if(!pw){\r\n");
      out.write("				loginForm.memberPw.focus();\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			loginForm.submit();\r\n");
      out.write("		} \r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	// 아이디를 전달받았다면, 아이디 저장을 눌러서 로그인 했다는 뜻.\r\n");
      out.write("		let memberId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("	// 비밀번호를 전달받았다면, 자동 로그인을 눌러서 로그인 했다는 뜻.\r\n");
      out.write("		let memberPw = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberPw}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("		\r\n");
      out.write("	// 위의 상황에 맞게 체크해주기!\r\n");
      out.write("		if(memberId){$(\"input[name='saveId']\").prop(\"checked\", true);}\r\n");
      out.write("		if(memberPw){$(\"input[name='autoLogin']\").prop(\"checked\", true);}\r\n");
      out.write("	</script>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /app/member/login.jsp(25,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty param.login}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("			<script>\r\n");
          out.write("				alert(\"아이디 또는 비밀번호를 다시 확인해주세요.\");\r\n");
          out.write("			</script>\r\n");
          out.write("		");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
