/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-24 06:51:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SchoolBoardWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/inyeo/Desktop/jsp/workspace/milestone/WebContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("jar:file:/C:/Users/inyeo/Desktop/jsp/workspace/milestone/WebContent/WEB-INF/lib/standard.jar!/META-INF/fn.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1664872564000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/board/schoolBoardWrite.css\"/>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"modifySchool\" style=\"padding-right: 4px;\">\r\n");
      out.write("        <header>\r\n");
      out.write("            <div id=\"headerBox\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"logo\" style=\"padding-top: 5px;height: 25px;\">\r\n");
      out.write("	        	       <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/board/logo.png\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"search_box\">\r\n");
      out.write("                    <input id=\"searchInput\" type=\"text\" placeholder=\"정을 옮기는 이정표입니다\">\r\n");
      out.write("               <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/board/search.png\">                \r\n");
      out.write("                  </div>\r\n");
      out.write("                <div class=\"user\">\r\n");
      out.write("                    <span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <div style=\"width: 20px;\"></div>\r\n");
      out.write("                    <span>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <div style=\"width: 20px;\"></div>\r\n");
      out.write("                    <div id=\"userWrap\">\r\n");
      out.write("                        <picture class=\"userIcon\">\r\n");
      out.write("                            <source type=\"image/webp\"\r\n");
      out.write("                                srcset=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/640xauto.webp 640w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/750xauto.webp 750w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/828xauto.webp 828w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1080xauto.webp 1080w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1200xauto.webp 1200w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto.webp 1920w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/2048xauto.webp 2048w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/3840xauto.webp 3840w\">\r\n");
      out.write("                            <img alt=\"profile\"\r\n");
      out.write("                                srcset=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/640xauto 640w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/750xauto 750w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/828xauto 828w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1080xauto 1080w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1200xauto 1200w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto 1920w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/2048xauto 2048w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/3840xauto 3840w\"\r\n");
      out.write("                                src=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27\"\r\n");
      out.write("                                loading=\"lazy\" class=\"css-1u3hmek\">\r\n");
      out.write("                        </picture>\r\n");
      out.write("                        <span id=\"bottomPointer\" style=\"position: absolute; left:96.4%; top:13px\">\r\n");
      out.write("                            <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\">\r\n");
      out.write("                                <path\r\n");
      out.write("                                    d=\"M2.075 8.825 3.49 7.41c.1-.1.255-.1.355 0L12 15.565l8.16-8.16c.1-.1.255-.1.355 0L21.93 8.82c.1.1.1.255 0 .355l-9.75 9.75c-.1.1-.255.1-.355 0L2.075 9.18c-.1-.1-.1-.26 0-.355Z\"\r\n");
      out.write("                                    class=\"css-17ivn46\"></path>\r\n");
      out.write("                            </svg>\r\n");
      out.write("                        </span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div id=\"miniBox\">\r\n");
      out.write("                    <div id=\"miniBox2\">\r\n");
      out.write("                        <div id=\"miniBox3\">\r\n");
      out.write("                            <div id=\"miniProfile\">\r\n");
      out.write("                                <img src=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto.webp\"\r\n");
      out.write("                                    alt=\"\">\r\n");
      out.write("                                <div style=\"margin: 10px;\">\r\n");
      out.write("                                     <div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nurserySchoolMemberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                    <div id=\"miniProfileRight\"><a href=\"myPage1.html \" style=\"color: orange;\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/404/404.jsp\"  style=\"text-decoration: none; color:black\">마이페이지</a>\r\n");
      out.write("                                            <svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\"\r\n");
      out.write("                                                class=\"css-jdqsvn\" style=\"width: 10px; height: 10px;\">\r\n");
      out.write("                                                <path\r\n");
      out.write("                                                    d=\"M8.825 21.93 7.41 20.515c-.1-.1-.1-.255 0-.355l8.155-8.155-8.16-8.16c-.1-.1-.1-.255 0-.355L8.82 2.075c.1-.1.255-.1.355 0l9.75 9.75c.1.1.1.255 0 .355L9.18 21.93c-.1.1-.26.1-.355 0Z\"\r\n");
      out.write("                                                    class=\"css-bchp3n\"></path>\r\n");
      out.write("                                            </svg>\r\n");
      out.write("                                        </a></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"css-1g5174\"></div>\r\n");
      out.write("                            <div style=\"text-align: center;\"> <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/index.me?logout=true\"  id=\"logout\" style=\"margin-right: 18px; text-decoration: none; color:black\"> 로그아웃</a></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div style=\"margin-left: 23px; font-size: 15px; font-weight: bold; color: rgb(26, 26, 26);\r\n");
      out.write("        line-height: 34px; padding-top : 10px ;margin-bottom :25px\">\r\n");
      out.write("            <h2 style=\"letter-spacing: -2.5px;\">글 작성하기</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("       <div class=\"sc-e489b3e-3 gEAbaC\" style=\"margin-top: -10px; margin-bottom: -20px;\">\r\n");
      out.write("           <div class=\"sc-e489b3e-7 dkxgGx\" style=\"padding-right: 20px; margin-left: 22px;\">\r\n");
      out.write("\r\n");
      out.write("               <!-- 프로필 사진 -->\r\n");
      out.write("               <div size=\"28\" class=\"sc-1602cde7-0 bvsxdu\">\r\n");
      out.write("                  <img sizes=\" 100vw\"\r\n");
      out.write("                    src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/board/smalluser.png\"\r\n");
      out.write("                    style=\"height: 30px; padding-right: 5px\">\r\n");
      out.write("               </div>\r\n");
      out.write("          <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/scboardwriteOk.schoolcom\" name=\"writeForm\" method=\"post\" enctype=\"multipart/form-data\" style=\"display: flex;align-items: center;\">         \r\n");
      out.write("               <!-- 작성자 -->\r\n");
      out.write("               <div class=\"writer\" md=\"Body2\" class=\"sc-8ee9b8f2-0 gBPcnX sc-e489b3e-8 eaqXQT\"\r\n");
      out.write("                   style=\"font-size : 14px; letter-spacing: -1px; padding-right: 394px;\">");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("</div>\r\n");
      out.write("    				<!-- 파일첨부 -->\r\n");
      out.write("    				<div class=\"files\">\r\n");
      out.write("	                   <div style=\"display: flex;\">\r\n");
      out.write("	                       <div class=\"image-upload\">\r\n");
      out.write("	                           <label for=\"file-input\" style=\"right: 20px;\">\r\n");
      out.write("	                           <img\r\n");
      out.write("	                             src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/board/putpicture.png\"\r\n");
      out.write("	                             style=\"height: 43px; cursor: pointer;position: absolute;right: 3%;top: 12%;\">\r\n");
      out.write("	                           </label>\r\n");
      out.write("                           <input name=\"individualCommunityImage\" id=\"file-input\" type=\"\" style=\"display: none;\"onclick=\"noReady()\"/>\r\n");
      out.write("							<!--<input name=\"individualCommunityImage\" id=\"file-input\" type=\"file\" style=\"display: none;\"onchange=\"javascript:document.getElementById('fileName').value = this.value.split('\\\\')[this.value.split('\\\\').length-1]\"/> -->\r\n");
      out.write("                           <!-- <input type=\"button\" onclick=\"cancelFile('board_file1')\" value=\"첨부 삭제\"> -->\r\n");
      out.write("	                       </div>\r\n");
      out.write("	                   </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <!-- 제목 -->\r\n");
      out.write("         <input id=\"boardTitle\" type=\"text\" placeholder=\"제목을 입력하세요\" name=\"nurserySchoolCommunityTitle\"\r\n");
      out.write("            style=\"padding: 16px; margin: 20px 20px 0 20px; width: 605px; height: 20px\">\r\n");
      out.write("         \r\n");
      out.write("            <!-- 내용 -->\r\n");
      out.write("         <div class=\"sc-e489b3e-9 iLCbOX\" style=\"margin: 20px; margin-right: 14px;\">\r\n");
      out.write("            <div class=\"sc-1f17b81e-1 fGEGPt postWrite\">\r\n");
      out.write("               <textarea id=\"boardContent\" class=\"sc-1f17b81e-0 dHJCuF sc-e489b3e-10 iTqZES  \"\r\n");
      out.write("                  placeholder=\"무단 홍보, 비방 글은 삭제될 수 있습니다.\" name=\"nurserySchoolCommunityContent\" autocomplete=\"off\"></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <!-- 첨부파일 -->\r\n");
      out.write("         <!-- 첨부파일 이름은 #fileName에 넣으세요 -->\r\n");
      out.write("         <div id=\"attachedFile\" style=\"padding: 0 20px 0 20px; color:rgb(190 190 190);\">         \r\n");
      out.write("            첨부된 파일:<input type=\"text\" id=\"fileName\" style=\"border-color:transparent\" readonly=\"readonly\">\r\n");
      out.write("         </div>\r\n");
      out.write("\r\n");
      out.write("       <div id=\"withdrawal\">\r\n");
      out.write("           <div id=\"content2\">\r\n");
      out.write("               <div id=\"first\">\r\n");
      out.write("                   <input type=\"button\" class=\"withdrawalSubmit\" id=\"save\" value=\"저장하기\" onclick=\"send()\"/>\r\n");
      out.write("               </div>\r\n");
      out.write("                   <input type=\"button\" style=\"margin-top:20px\" class=\"cancel\" id=\"save\" value=\"취소하기\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/board/schoolBoard.schoolcom'\" class=\"lists\"/>\r\n");
      out.write("           </div>\r\n");
      out.write("       </div>\r\n");
      out.write("   </form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/board/schoolBoardWrite.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("function noReady(){\r\n");
      out.write("	alert(\"페이지 준비중입니다\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function send(){\r\n");
      out.write("   console.log(writeForm.nurserySchoolCommunityTitle.value);\r\n");
      out.write("   console.log(writeForm.nurserySchoolCommunityContent.value);\r\n");
      out.write("   \r\n");
      out.write("   if(!$(\"#boardTitle\")){\r\n");
      out.write("      alert(\"제목을 작성해주세요.\");\r\n");
      out.write("      return;\r\n");
      out.write("   }\r\n");
      out.write("   if(!$(\"#boardContent\")){\r\n");
      out.write("      alert(\"내용을 작성해주세요.\");\r\n");
      out.write("      return;\r\n");
      out.write("   }\r\n");
      out.write("   writeForm.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(\".files\").change(function(e){\r\n");
      out.write("    var file = e.target.files[0];\r\n");
      out.write("    var img = $(this).find(\"img\");\r\n");
      out.write("    var reader = new FileReader();\r\n");
      out.write("    reader.readAsDataURL(file);\r\n");
      out.write("    \r\n");
      out.write("     reader.onload = function(e){\r\n");
      out.write("        if(e.target.result.indexOf(\"image\") != -1){\r\n");
      out.write("           img.attr(\"src\", e.target.result)\r\n");
      out.write("        }else{\r\n");
      out.write("           /* img.attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/no_img.jpg\"); */\r\n");
      out.write("        }\r\n");
      out.write("     }\r\n");
      out.write("  });\r\n");
      out.write(" \r\n");
      out.write(" function cancelFile(fileName){\r\n");
      out.write("    $(\"input#\" + fileName).val(\"\");\r\n");
      out.write("    $(\"img#\" + fileName + \"Img\").attr(\"src\", \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/filePlus.png\");\r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /app/board/SchoolBoardWrite.jsp(103,89) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nurserySchoolMemberId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
