/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-10-24 09:51:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.app.donation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class donationProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/inyeo/Desktop/jsp/workspace/milestone/WebContent/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1664872564000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>물품기부 결제창</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"payment.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"modify.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/donation/payment.css\" />\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/myPage/modify.css\" />\r\n");
      out.write("<style>\r\n");
      out.write("@font-face {\r\n");
      out.write("	font-family: 'Pretendard-Regular';\r\n");
      out.write("	src:\r\n");
      out.write("		url('https://cdn.jsdelivr.net/gh/Project-Noonnu/noonfonts_2107@1.1/Pretendard-Regular.woff')\r\n");
      out.write("		format('woff');\r\n");
      out.write("	font-weight: 400;\r\n");
      out.write("	font-style: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	font-family: 'Pretendard-Regular';\r\n");
      out.write("	margin-left: 0px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"background-color: #f8f8f9;\">\r\n");
      out.write("	<div id=\"modifySchool\">\r\n");
      out.write("		<header>\r\n");
      out.write("			<div id=\"headerBox\">\r\n");
      out.write("				<div class=\"logo\">\r\n");
      out.write("					<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/index.me\">\r\n");
      out.write("						<div class=\"logo\">\r\n");
      out.write("							<img\r\n");
      out.write("								src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/donation/logo.png\">\r\n");
      out.write("						</div>\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"search_box\">\r\n");
      out.write("					<input id=\"searchInput\" type=\"text\" placeholder=\"정을 옮기는 이정표입니다\"><img\r\n");
      out.write("						src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/donation/search.png\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"user\">\r\n");
      out.write("\r\n");
      out.write("					<div style=\"width: 20px;\"></div>\r\n");
      out.write("					<div id=\"userWrap\">\r\n");
      out.write("						<picture class=\"userIcon\">\r\n");
      out.write("						<source type=\"image/webp\"\r\n");
      out.write("							srcset=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/640xauto.webp 640w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/750xauto.webp 750w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/828xauto.webp 828w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1080xauto.webp 1080w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1200xauto.webp 1200w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto.webp 1920w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/2048xauto.webp 2048w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/3840xauto.webp 3840w\">\r\n");
      out.write("						<img alt=\"profile\"\r\n");
      out.write("							srcset=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/640xauto 640w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/750xauto 750w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/828xauto 828w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1080xauto 1080w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1200xauto 1200w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto 1920w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/2048xauto 2048w,https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/3840xauto 3840w\"\r\n");
      out.write("							src=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27\"\r\n");
      out.write("							loading=\"lazy\" class=\"css-1u3hmek\"> </picture>\r\n");
      out.write("						<span id=\"bottomPointer\"\r\n");
      out.write("							style=\"position: absolute; left: 92%; top: 13px\"> <svg\r\n");
      out.write("								xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\"\r\n");
      out.write("								style=\"padding-left: 16px;\">\r\n");
      out.write("                <path\r\n");
      out.write("									d=\"M2.075 8.825 3.49 7.41c.1-.1.255-.1.355 0L12 15.565l8.16-8.16c.1-.1.255-.1.355 0L21.93 8.82c.1.1.1.255 0 .355l-9.75 9.75c-.1.1-.255.1-.355 0L2.075 9.18c-.1-.1-.1-.26 0-.355Z\"\r\n");
      out.write("									class=\"css-17ivn46\"></path>\r\n");
      out.write("              </svg>\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div id=\"miniBox\">\r\n");
      out.write("					<div id=\"miniBox2\">\r\n");
      out.write("						<div id=\"miniBox3\">\r\n");
      out.write("							<div id=\"miniProfile\">\r\n");
      out.write("								<img\r\n");
      out.write("									src=\"https://cdn.class101.net/images/cba86b3c-f6a4-42b3-9bbd-bf6c09e49d27/1920xauto.webp\"\r\n");
      out.write("									alt=\"\">\r\n");
      out.write("								<div style=\"margin: 10px;\">\r\n");
      out.write("                                    <div>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${individualMemberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("                                    <div id=\"miniProfileRight\"><a href=\"myPage1.html\"><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/app/404/404.jsp\"  style=\"text-decoration: none; color:rgb(255 114 42)\">마이페이지</a> \r\n");
      out.write("										<svg\r\n");
      out.write("												xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\"\r\n");
      out.write("												class=\"css-jdqsvn\" style=\"width: 10px; height: 10px;\">\r\n");
      out.write("                        <path\r\n");
      out.write("													d=\"M8.825 21.93 7.41 20.515c-.1-.1-.1-.255 0-.355l8.155-8.155-8.16-8.16c-.1-.1-.1-.255 0-.355L8.82 2.075c.1-.1.255-.1.355 0l9.75 9.75c.1.1.1.255 0 .355L9.18 21.93c-.1.1-.26.1-.355 0Z\"\r\n");
      out.write("													class=\"css-bchp3n\"></path>\r\n");
      out.write("                      </svg>\r\n");
      out.write("										</a>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"css-1g5174\"></div>\r\n");
      out.write("							<a class=\"logout\"\r\n");
      out.write("								href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/index.me?logout=true\"\r\n");
      out.write("								style=\"text-align: center;\">로그아웃</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"all-body\"></div>\r\n");
      out.write("		<div class=\"body-header-padding\">\r\n");
      out.write("			<div class=\"body-header-flex\">\r\n");
      out.write("				<h3 class=\"body-header-title\" style=\"margin-right: 66%;\">기부하기</h3>\r\n");
      out.write("				<div class=\"body-header-subTitle\">\r\n");
      out.write("					<div class=\"protect-img\"></div>\r\n");
      out.write("					<div class=\"protect-img-title\">암호화 중</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"white-space\" style=\"margin: 0;\"></div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"content\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"flex\">\r\n");
      out.write("				<div class=\"marginBottom16\" style=\"margin-bottom: 0\">\r\n");
      out.write("					<div class=\"contents-title\">물품 기부하기</div>\r\n");
      out.write("					<div style=\"display: flex;\">\r\n");
      out.write("						<div style=\"margin: 20px 0 15px 25px\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div style=\"margin: 0 0 35px 10px\">\r\n");
      out.write("						마일스톤은 물품기부는 방문 수거로 진행되고 있습니다. <br>물품기부를 신청하시면 추후 연락을 통해 방문\r\n");
      out.write("						예정입니다.\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"items-background-no\">\r\n");
      out.write("					<div class=\"items-img-pencel\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			<div class=\"marginBottom16\">\r\n");
      out.write("				<form\r\n");
      out.write("					action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/donation/donationProductOk.don\"\r\n");
      out.write("					name=\"donationForm\">\r\n");
      out.write("					<input type=\"hidden\" name=\"nurserySchoolMemberNumber\"\r\n");
      out.write("						value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nurserySchoolMemberNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"contents-sub-title\">방문날짜</div>\r\n");
      out.write("						<div class=\"contents-margin-top\" style=\"margin-bottom: 12px\">\r\n");
      out.write("							<div class=\"flex\">\r\n");
      out.write("								<div class=\"contents-input-box\"\r\n");
      out.write("									style=\"display: flex; width: 100%\">\r\n");
      out.write("									<input type=\"date\" name=\"donationDate\" style=\"width: 95%\">\r\n");
      out.write("									<div class=\"contents-sub-title\"></div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"width8\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"contents-sub-title\">기부물품 종류</div>\r\n");
      out.write("						<div class=\"contents-margin-top\" style=\"margin-bottom: 12px;\">\r\n");
      out.write("							<div class=\"flex\" style=\"width: 30%\">\r\n");
      out.write("								<div class=\"contents-input-box\">\r\n");
      out.write("									<div class=\"selectbox\" style=\"width: 330%;\">\r\n");
      out.write("										<input type = \"hidden\" name = \"donationProducts\" value = \"\">\r\n");
      out.write("										<label for=\"donationProducts\">종류</label> <select\r\n");
      out.write("											id=\"donationProducts\">\r\n");
      out.write("											<option value=\"생필품\" class=\"test\">생필품</option>\r\n");
      out.write("											<option value=\"음식\" class=\"test\">음식</option>\r\n");
      out.write("											<option value=\"가구\" class=\"test\">가구</option>\r\n");
      out.write("											<option value=\"기타\" class=\"test\">기타</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<div class=\"contents-sub-title\">물품 상세</div>\r\n");
      out.write("							<div class=\"contents-margin-top\" style=\"margin-bottom: 12px\">\r\n");
      out.write("								<div class=\"flex\">\r\n");
      out.write("									<div class=\"contents-input-box\">\r\n");
      out.write("										<input type=\"text\" name=\"donationDetailProducts\"\r\n");
      out.write("											style=\"width: 117%\" placeholder=\"예) 옷, 가방 노트북, ...\">\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div class=\"contents-sub-title\">수량</div>\r\n");
      out.write("						<div class=\"contents-margin-top\" style=\"margin-bottom: 12px\">\r\n");
      out.write("							<div class=\"flex\">\r\n");
      out.write("								<div class=\"contents-input-box\"\r\n");
      out.write("									style=\"display: flex; width: 100%;\">\r\n");
      out.write("									<input type=\"text\" name=\"quantity\" style=\"width: 95%\">\r\n");
      out.write("									<div class=\"contents-sub-title\"\r\n");
      out.write("										style=\"display: flex; align-items: center;\">&nbsp;개</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"width8\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"contents-sub-title\">Box수량</div>\r\n");
      out.write("						<div class=\"contents-margin-top\" style=\"margin-bottom: 12px\">\r\n");
      out.write("							<div class=\"flex\">\r\n");
      out.write("								<div class=\"contents-input-box\"\r\n");
      out.write("									style=\"display: flex; width: 100%\">\r\n");
      out.write("									<input type=\"text\" name=\"boxQuantity\" style=\"width: 95%\">\r\n");
      out.write("									<div class=\"contents-sub-title\"\r\n");
      out.write("										style=\"display: flex; align-items: center; width: 34px;\">&nbsp;박스</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"width8\"></div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("				<div class=\"white-space\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				<div style=\"height: 8px;\"></div>\r\n");
      out.write("				<div class=\"flex\">\r\n");
      out.write("					<div class=\"marginBottom16\">\r\n");
      out.write("						<div class=\"contents-title\">수거 신청</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<button class=\"submit-button flex-center\"\r\n");
      out.write("					style=\"font-size: 14px; font-weight: 700; cursor: pointer; margin-top: 17px; background-color: rgb(255, 242, 233);\">물품기부\r\n");
      out.write("					신청하기</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div style=\"height: 8px;\"></div>\r\n");
      out.write("	<footer class=\"foot\">\r\n");
      out.write("		<div style=\"padding: 24px; width: 600px; height: 200px;\">\r\n");
      out.write("			<img\r\n");
      out.write("				src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/img/donation/logo.png\"\r\n");
      out.write("				style=\"width: 158px;\">\r\n");
      out.write("			<h5>Milestone 프로젝트는 보육원의 모든 아이들이 사랑받고 아름답게 성장하길 기원합니다.</h5>\r\n");
      out.write("			<p>Milestome Korea</p>\r\n");
      out.write("			<p>Instagram · Youtube · Facebook · Naverpost</p>\r\n");
      out.write("			<p>Naverblog · Playstore · Appstore</p>\r\n");
      out.write("			<p>이용약관 · 개인정보 처리방침 · 이용약관 · 사업자 정보 확인 · 제휴/협력 · 문의 단체/기업 교육 문의</p>\r\n");
      out.write("			<p>동석한 아카데미 Team 4 | 대표 김의엽 | 서울 강남구 테헤란로 146 3층(역삼동) | T4@.inc |\r\n");
      out.write("				전화번호: 1234-1234 |</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/donation/donationProduct.js\"></script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
